version: '3.8'

services:
  connect_ease_database:
    image: mongo:7.0
    container_name: connect_ease_db
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodata:/data/db
    networks:
      - connect_ease

volumes:
  mongodata:
    driver: local

networks:
  connect_ease:
